version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: nginx_webserver
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
